config/routes.rb
# frozen_string_literal: true

Litera::Engine.routes.draw do
  resources :messages, only: %i[index show]
end

app/models/litera/application_record.rb
# frozen_string_literal: true

module Litera
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/litera/message.rb
# frozen_string_literal: true

module Litera
  class Message < ApplicationRecord
    validates :body, presence: true
    validates :service, presence: true
    validates :metadata, presence: true
    validates :external_id, presence: true
    validates :published_at, presence: true

    scope :ordered, -> { order(published_at: :desc) }
  end
end

app/controllers/litera/application_controller.rb
# frozen_string_literal: true

module Litera
  class ApplicationController < Litera.parent_controller.constantize
    before_action :authorize_litera_user

    private

    def litera_user
      send(Litera.litera_user)
    end

    def authorize_litera_user
      return if Litera.authorization.call(litera_user)

      raise Litera::Errors::NotAuthorized
    end
  end
end

app/controllers/litera/messages_controller.rb
# frozen_string_literal: true

module Litera
  class MessagesController < ApplicationController
    include Pagy::Backend

    def index
      @pagy, @messages = pagy(Message.ordered)
    end

    def show
      @message = Message.find(params[:id])
    end
  end
end

app/helpers/litera/application_helper.rb
# frozen_string_literal: true

module Litera
  module ApplicationHelper
    include Pagy::Frontend
  end
end

app/views/layouts/litera/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Litera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "litera/application", media: "all" %>
  </head>

  <body class="litera">
    <%= yield %>
  </body>
</html>

app/views/litera/messages/index.html.erb
<h1><%= Litera::Message.model_name.human(count: 2) %></h1>

<table width="100%">
  <thead>
    <tr>
      <th><%= Litera::Message.human_attribute_name(:published_at) %></th>
      <th><%= Litera::Message.human_attribute_name(:service) %></th>
      <th><%= Litera::Message.human_attribute_name(:id) %></th>
      <th><%= Litera::Message.human_attribute_name(:metadata) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= l(message.published_at) %></td>
        <td><%= message.service %></td>
        <td><%= message.external_id %></td>
        <td><%= message.metadata.to_s.truncate(50).html_safe %></td>
        <td><%= link_to t(".show"), message %></td>
      </tr>
    <% end %>
  </body>
</table>

<%== pagy_nav(@pagy) %>

app/views/litera/messages/show.html.erb
<h1>Message: <%= @message.external_id %></h1>

<table>
  <tbody>
    <tr>
      <th><%= Litera::Message.human_attribute_name(:published_at) %></th>
      <td><%= l(@message.published_at) %></td>
    </tr>

    <tr>
      <th><%= Litera::Message.human_attribute_name(:service) %></th>
      <td><%= @message.service %></td>
    </tr>

    <tr>
      <th><%= Litera::Message.human_attribute_name(:id) %></th>
      <td><%= @message.external_id %></td>
    </tr>

    <tr>
      <th><%= Litera::Message.human_attribute_name(:metadata) %></th>
      <td><pre><%= JSON.pretty_generate(@message.metadata) %></pre></td>
    </tr>

    <tr>
      <th><%= Litera::Message.human_attribute_name(:body) %></th>
      <td><pre><%= JSON.pretty_generate(@message.body) %></pre></td>
    </tr>
  </body>
</table>

<%= link_to t(".back"), messages_path %>